build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                coverage:
                    file: './coverage/coverage-clover.xml'
                    format: 'clover'
